# Railway Nixpacks Configuration
[nixpacks]
provider = "python"

[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["pip install -r requirements-railway.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python railway_bot.py"
